from setuptools import find_packages, setup


setup(
    name='tcenter',
    packages=find_packages(include=['tcenter']),
    version='0.1.3.1',
    description='A library for center titles',
    author='Evandro Silva',
    license='MIT',
    install_requires=[],
    setup_requires=[],
    tests_requires=['pytest==6.2.3'],
    tests_suite=['tests'],
    author_email='evandrojunior1615@gmail.com',
    url='https://github.com/Suspir0n/tcenter',
    download_url='https://github.com/Suspir0n/tcenter/archive/refs/tags/0.1.3.1.tar.gz',
    python_requires='>=3.6',
    classifiers=[
        'Development Status :: 0.1.3.1 - Production/Stable',
        'Environment :: Other Environment',
        'Intended Audience :: Developers',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Topic :: Software Development',
        'Topic :: Utilities',
        'License :: MIT',
    ],
    maintainer='Evandro Silva',
    maintainer_email='evandrojunior1615@gmail.com',
)